### ISSUE TITLE
Add comments for all important lines

### ISSUE THREAD

**Issue by jininvt** [monna-lee/rock-paper-scissors#2]
For example, on lines 3, 8 and 10 (of commit 06cf314fce32ccb445b51001d7b546d96945ac07) you need to elaborate on what you're doing. 

Why are you using the typing library? What is the List type and why do you need to import it?

**Comment by jininvt** [comment]
@monna-lee Please respond to this issue and close it and state the commit ID once you've fixed this.

**Comment by monna-lee** [comment]
> @monna-lee Please respond to this issue and close it and state the commit ID once you've fixed this.

83bb94d819bfcb9186b0758ff7e7bd7aca62da18
